language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
install:
 - pip install -r requirements.txt coverage coveralls
 - python download_corpora.py
script:
  - coverage run --source newspaper tests/unit_tests.py
after_success:
  coveralls
