from gnews.utils.constants import (
    AVAILABLE_COUNTRIES as AVAILABLE_COUNTRIES,
    AVAILABLE_LANGUAGES as AVAILABLE_LANGUAGES,
    GOOGLE_NEWS_REGEX as GOOGLE_NEWS_REGEX,
)

def lang_mapping(lang): ...
def country_mapping(country): ...
def connect_database(db_user, db_pw, db_name, collection_name): ...
def post_database(collection, news) -> None: ...
def process_url(item, exclude_websites): ...
